
vscode:
  extensions:
    - mongodb.mongodb-vscode
ports:
    - port: 3000-8999
      onOpen: ignore
tasks:
  - init: |
      echo "Pulling MongoDB..."
      docker pull mongo
      echo "Preparing MonboDB Instance"
      docker run --name mymongo -d -p 27017:27017 mongo
      npm install
      echo "Starting Node Server..."
      node server.js


      
  
