version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mymongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: todoapp
    container_name: todoapp-container
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
    driver: bridge
